### PR TITLE
Added Centos Support 

### PR DESCRIPTION
**Pull request by chilicat**
Added centos support.

### CODE REVIEW

**Comment by joschi** [comment]
Merged in 5f63a7e4e9823d4e0bc7e0862664c8f1c5d4db98 and updated on the forge. Thanks for your patch!

**Comment by chilicat** [comment]
Just figured out that it is needed to install kernel-headers, make, gcc packages to make virtualbox functional. The reason for that is that virtual box tries to compile a kernel module. My first test system had this packages already be installed :)

Do you think it make sense to install the packages as part of the puppet module or should it be a pre-requisite?
Does this problem also occur on Debian/Ubuntu?

**Comment by joschi** [comment]
I just checked the Debian package for Debian Squeeze but the other DEB packages should be similar.

The package "recommends" the packages `gcc` and `linux-headers` (and some other build-related tools) which means it declares them as optional dependencies. Since the packaging system was configured to automatically install optional dependencies (using the setting `APT::Get::Install-Recommends`) these build tools were installed along with the VirtualBox package.

I don't think that this Puppet module should install the build tools explicitly but maybe offer a parameter named `require_buildtools` or similar. What's your opinion on that?

**Comment by chilicat** [comment]
I don' know what exactly you mean with additional parameter (I'm new to puppet development). 
Do you mean to add new class virtualbox::require_buildtools which can be declared if the user wishes to install the build tools?

**Comment by joschi** [comment]
> Do you mean to add new class virtualbox::require_buildtools which can be declared if the user wishes to install the build tools?

Yes, exactly. This would explicitly mention the dependencies of the module although it looks "strange".

As an alternative we could simply use Puppet's meta-parameter `require` (or the arrows `->`) to declare dependencies but this would mean that every user of the module needs to add this by herself.

**Pull request closed without merging**
